import React, { Component } from "react";
import "./Home.css";
import Button from "../../components/Button/Button";
//import Customers from "../../containers/Customers/Customers";
import MediaItems from "../../components/MediaItems/MediaItems";
import axios from "axios";

class Home extends Component {
  state = {
    selectedFile: { name: "null" },
    media: [],
    uploadDisabled: true
  };
  //Request get media - using in Mount (componentDidMount) and when Updating the media (Sending any other requests, e.g Post)
  updateMediaHandler = () => {
    console.log("The current array: ");
    console.log(this.state.media);
    axios
      .get("/api/media")
      .then(media => this.setState({ media: media.data }))
      .catch(err => console.log(err));
  };

  componentDidMount() {
    console.log(
      "The media [] state is initialized (client Mount of Home component)"
    );
    this.updateMediaHandler();
  }

  //selectedFile is generated by user's choice
  fileSelectedHandler = e => {
    e.preventDefault();
    console.log(" fileSelectedHandler invoked");

    //if the user selected a file, than selectedFile == input, upload button is enabled
    if (e.target.files.length > 0) {
      console.log(e.target.files[0]);

      this.setState({
        selectedFile: e.target.files[0],
        uploadDisabled: false
      });
    }
  };

  fileUploadHandler = e => {
    e.preventDefault();
    console.log(" fileUploadHandler invoked");

    if (this.state.selectedFile != null) {
      const newImage = {
        name: this.state.selectedFile.name,
        path: window.URL.createObjectURL(this.state.selectedFile)
      };

      axios
        .post("/api/media", newImage)
        .then(res => {
          console.log(res.data);
          this.updateMediaHandler();
        })
        .catch(err => console.log(err));

      this.setState({
        selectedFile: null,
        uploadDisabled: !this.state.uploadDisabled
      });
    }
  };

  render() {
    return (
      <React.Fragment>
        <div className="backgroundHome"></div>
        <div className="Home">
          <h1>Welcome to my Uploading website</h1>
          <h2>Click on the browse button in order to upload media!</h2>
          <input
            type="file"
            onChange={this.fileSelectedHandler}
            accept="image/*"
            style={{ display: "none" }}
            ref={fileInput => (this.fileInput = fileInput)}
          />
          <Button
            name="Browse"
            click={() => this.fileInput.click()}
            type="button"
          ></Button>

          <Button
            name="Upload"
            click={this.fileUploadHandler}
            disabled={this.state.uploadDisabled}
          />

          <MediaItems
            media={this.state.media}
            update={this.updateMediaHandler}
          />
        </div>
      </React.Fragment>
    );
  }
}

export default Home;
