import React, { Component } from "react";
import "./Home.css";
import Button from "../../components/Button/Button";
import axios from "axios";
import Spinner from "../../components/Spinner/Spinner";
class Home extends Component {
  state = {
    selectedFile: { name: "null" },
    media: this.props.media,
    uploadDisabled: this.props.uploadDisabled
  };

  //Returns true if a file's type is image regardless it's type
  isFileImage = file => {
    return file && file["type"].split("/")[0] === "image";
  };

  //selectedFile is generated by user's choice
  fileSelectedHandler = e => {
    console.log("fileSelectedHandler invoked");

    //if the user selected a file, than selectedFile == input, upload button is enabled
    if (e.target.files.length > 0) {
      console.log(e.target.files[0]);

      if (!this.isFileImage(e.target.files[0])) {
        console.log(
          "The selected file is NOT an image - ADD A POP UP COMPONENT"
        );
      } else {
        this.setState({
          selectedFile: e.target.files[0],
          uploadDisabled: false
        });
      }
    }
  };

  fileUploadHandler = e => {
    e.preventDefault();
    console.log("fileUploadHandler invoked");

    if (this.state.selectedFile != null) {
      const newImage = {
        name: this.state.selectedFile.name,
        path: window.URL.createObjectURL(this.state.selectedFile)
      };
      this.props.updateLoadingHandler();
      axios
        .post("/api/media", newImage)
        .then(res => {
          console.log(res.data);
          this.props.updateMediaHandler();
        })
        .catch(err => console.log(err));

      this.setState({
        selectedFile: null,
        uploadDisabled: !this.state.uploadDisabled
      });
    }
  };

  render() {
    let spinner = null;

    if (this.props.loading) {
      spinner = <Spinner />;
    } else {
      spinner = null;
    }

    return (
      <>
        {spinner}
        <div className="Home">
          <h1>Welcome to my Uploading website</h1>
          <h2>Click on the browse button in order to upload media!</h2>
          <input
            type="file"
            onChange={this.fileSelectedHandler}
            accept="image/*"
            style={{ display: "none" }}
            ref={fileInput => (this.fileInput = fileInput)}
          />
          <Button
            name="Browse"
            click={() => this.fileInput.click()}
            type="button"
          ></Button>

          <Button
            name="Upload"
            click={this.fileUploadHandler}
            disabled={this.state.uploadDisabled}
          />
          {/* <MediaItems
            media={this.state.media}
            update={this.updateMediaHandler}
          /> */}

          {/* <Route
            path="/media"
            exact
            render={props => (
              <MediaItems
                media={this.state.media}
                update={this.state.updateMediaHandler}
                {...props}
              />
            )}
          /> */}
        </div>
      </>
    );
  }
}

export default Home;
